# Generated by Django 5.1.7 on 2025-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlShortening', '0002_url_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
